import mongoose from 'mongoose';
import dotenv from 'dotenv';
import bcrypt from 'bcryptjs';
import User from '../models/User.js';
import Category from '../models/Category.js';
import Product from '../models/Product.js';
import Order from '../models/Order.js';
import Cart from '../models/Cart.js';
import Wishlist from '../models/Wishlist.js';

dotenv.config();

const u = (id) => `https://images.unsplash.com/photo-${id}?w=800&q=80&auto=format&fit=crop`;

const CATEGORIES_DATA = [
  { name: 'Handloom',      slug: 'handloom',      icon: '🧵', description: 'Authentic hand-woven textiles from across India' },
  { name: 'Handicrafts',   slug: 'handicrafts',   icon: '🏺', description: 'Handcrafted artifacts by skilled Indian artisans' },
  { name: 'Fashion',       slug: 'fashion',       icon: '👗', description: 'Indian fashion — sarees, kurtas, ethnic wear' },
  { name: 'Jewellery',     slug: 'jewellery',     icon: '💍', description: 'Traditional and contemporary Indian jewellery' },
  { name: 'Home Decor',    slug: 'home-decor',    icon: '🏡', description: 'Handcrafted home décor from Indian artisans' },
  { name: 'Ayurveda',      slug: 'ayurveda',      icon: '🌿', description: 'Authentic Ayurvedic wellness and skincare' },
  { name: 'Kitchen',       slug: 'kitchen',       icon: '☕', description: 'Traditional Indian kitchen & cooking essentials' },
  { name: 'Books',         slug: 'books',         icon: '📚', description: 'Indian literature, heritage and craft books' },
];

const buildProducts = (categoryMap) => [
  // ─── HANDLOOM ─────────────────────────────────────────────────────────────
  { name:'Chanderi Silk-Cotton Saree – Block Printed', brand:'Taneira', category:categoryMap['Handloom'], images:[u('1583241800-9f8e5b2f0f46')], price:4200, discount:10, stock:25, state:'Madhya Pradesh', craftType:'Chanderi Weaving', isMSME:true, isSustainable:true, isFeatured:true, description:'Hand-block-printed Chanderi saree woven by MSME artisans in Madhya Pradesh. Light-weight silk-cotton blend with gold zari border.', history:'Chanderi silk traces back to Vedic times and was patronised by Mughal royalty.', materials:'Organic silk-cotton blend, gold zari', artisan:'Bunkaar Society, Chanderi', specifications:[{key:'Length',value:'5.5 metres + blouse piece'},{key:'Width',value:'44 inches'},{key:'Material',value:'70% silk, 30% cotton'},{key:'Care',value:'Dry clean only'}] },
  { name:'Pochampally Ikat Silk Dupatta – Deep Indigo', brand:'Pochampally Weavers', category:categoryMap['Handloom'], images:[u('1585386959-a4a9b3b4b8fc')], price:1800, discount:0, stock:40, state:'Telangana', craftType:'Ikat Weaving', isMSME:true, isSustainable:true, isFeatured:false, description:'Double Ikat silk dupatta from Pochampally, featuring mirror-symmetric geometric patterns created by resist-dyeing both warp and weft.', history:'Pochampally Ikat is a UNESCO-recognised GI-tagged craft of Telangana.', materials:'Mulberry silk, vegetable dyes', artisan:'Pochampally Handloom Co-op', specifications:[{key:'Length',value:'2.5 metres'},{key:'Width',value:'42 inches'}] },
  { name:'Kanjivaram Silk Saree – Temple Border', brand:'Palam Silks', category:categoryMap['Handloom'], images:[u('1610030169-4d0c0ef6d26d')], price:18000, discount:5, stock:15, state:'Tamil Nadu', craftType:'Kanjivaram Weaving', isMSME:true, isSustainable:false, isFeatured:true, description:'Authentic Kanchipuram silk saree with 22kt gold zari temple border. Each saree takes 4–6 weeks on a traditional handloom.', history:'Kanchipuram silk weaving has a 400-year legacy in Tamil Nadu.', materials:'Pure mulberry silk, 22kt gold zari', artisan:'Kanchipuram Silk Society', specifications:[{key:'Zari',value:'22kt gold'},{key:'Weight',value:'800 grams'}] },
  { name:'Khadi Hand-Spun Cotton Kurta', brand:'Fab India', category:categoryMap['Handloom'], images:[u('1594938298608-ec58f5d3e4cb')], price:1250, discount:15, stock:60, state:'Gujarat', craftType:'Khadi Weaving', isMSME:true, isSustainable:true, isFeatured:false, description:'Pure hand-spun khadi cotton kurta in natural off-white. KVIC certified. Ideal for everyday sustainable fashion.', history:"Khadi was revived by Gandhi's Swadeshi movement.", materials:'100% hand-spun organic cotton', artisan:'KVIC, Gujarat', specifications:[{key:'Sizes',value:'S/M/L/XL/XXL'},{key:'Washing',value:'Machine wash cold'}] },
  { name:'Sambalpuri Ikat Cotton Saree', brand:'Loom India', category:categoryMap['Handloom'], images:[u('1583241800-6e6e4bfde2f2')], price:3400, discount:0, stock:30, state:'Odisha', craftType:'Sambalpuri Ikat', isMSME:true, isSustainable:true, isFeatured:false, description:'Handwoven Sambalpuri saree with Shankha and Chakra ikat motifs. Entirely produced by tribal weavers in Odisha.', history:'Sambalpuri ikat uses ancient resist-dyeing techniques.', materials:'Fine cotton yarn, vegetable dyes', artisan:'Sambalpur Handloom Cluster', specifications:[{key:'Length',value:'5.5m'},{key:'Blouse',value:'Included'}] },
  { name:'Banarasi Kinkhab Silk Fabric – Per Metre', brand:'Ekaya Banaras', category:categoryMap['Handloom'], images:[u('1519710164-3b9c3e5ee7be')], price:4200, discount:0, stock:50, state:'Uttar Pradesh', craftType:'Kinkhab Brocade', isMSME:true, isSustainable:false, isFeatured:true, description:'The most complex Banarasi brocade — pure silk woven with dense silver and gold zari motifs. GI-tagged craft of Varanasi.', history:'Kinkhab brocade was the fabric of Mughal royalty.', materials:'Pure silk, silver and gold zari', artisan:'Varanasi Silk Brocade Cooperative', specifications:[{key:'Width',value:'44 inches'},{key:'Sold',value:'Per metre'}] },
  { name:'Kashmiri Pashmina Shawl – Natural Grey', brand:'Shingora', category:categoryMap['Handloom'], images:[u('1544966503-7f56c85f1f4e')], price:8900, discount:8, stock:20, state:'Jammu & Kashmir', craftType:'Pashmina Weaving', isMSME:false, isSustainable:true, isFeatured:true, description:'Grade-A Pashmina hand-combed from Changthangi goats of Ladakh, woven on traditional handlooms. Certificate of authenticity included.', history:'Pashmina has been Ladakh\'s premium export for 600+ years.', materials:'Grade-A Pashmina, natural pigments', artisan:'Kashmir Pashmina Craft Council', specifications:[{key:'Size',value:'70×200 cm'},{key:'Weight',value:'120 grams'}] },
  { name:'Assam Muga Silk Mekhela Chador', brand:'Silkworm Assam', category:categoryMap['Handloom'], images:[u('1610030169-6e6e4bfde2f2')], price:6800, discount:0, stock:18, state:'Assam', craftType:'Muga Silk Weaving', isMSME:true, isSustainable:true, isFeatured:false, description:'Rare golden Muga silk from Assam — the only wild silk with a natural golden sheen that deepens with every wash.', history:'Muga silk is unique to Assam and produced from wild Antheraea assamensis silkworms.', materials:'Wild Muga silk cocoons', artisan:'Sualkuchi Weaving Cluster', specifications:[{key:'Occasion',value:'Bihu, Weddings'},{key:'Care',value:'Dry clean recommended'}] },
  { name:'Phulkari Embroidered Dupatta – Punjab', brand:'Amrapali', category:categoryMap['Handloom'], images:[u('1594938298608-5a9d524b3d5b')], price:2200, discount:5, stock:35, state:'Punjab', craftType:'Phulkari Embroidery', isMSME:true, isSustainable:true, isFeatured:false, description:'Traditional Phulkari flower-work embroidered on handwoven cotton. Artisans use 36 distinct stitches for this GI-tagged craft of Punjab.', history:'Phulkari embroidery has been practised for over 500 years in Punjab.', materials:'Handwoven cotton, silk floss thread', artisan:'Punjab Phulkari Artisan Collective', specifications:[{key:'Size',value:'100×250 cm'},{key:'Colours',value:'Multiple'}] },
  { name:'Naga Tribal Loin-Loom Stole', brand:'North East Roots', category:categoryMap['Handloom'], images:[u('1519710164-8b9c3e5ee7be')], price:2200, discount:0, stock:22, state:'Nagaland', craftType:'Naga Loin-Loom', isMSME:true, isSustainable:true, isFeatured:false, description:'Handwoven by Naga tribal women on back-strap loin looms in bold ceremonial stripe patterns unique to each sub-tribe.', history:'Naga loin-loom weaving uses body-tension for tight, sturdy fabric.', materials:'Wild cotton, natural earth dyes', artisan:'Nagaland Tribal Weavers Union', specifications:[{key:'Dimensions',value:'60×200 cm'}] },
  { name:'Kota Doria Silk-Cotton Saree', brand:'Rajsilk', category:categoryMap['Handloom'], images:[u('1610030169-1d0c1ef6d26d')], price:3900, discount:10, stock:28, state:'Rajasthan', craftType:'Kota Doria Weaving', isMSME:true, isSustainable:true, isFeatured:false, description:'Ultra-lightweight Kota Doria saree with characteristic square-check (khat) pattern woven in silk-cotton blend. Ideal for summer.', history:'Kota Doria weaving originated in Kaithoon, Kota.', materials:'Silk-cotton blend, gold zari accents', artisan:'Kaithoon Handloom Cluster', specifications:[{key:'Weight',value:'300 grams'},{key:'Transparency',value:'Semi-sheer'}] },
  { name:'Kullu Woollen Shawl – Geometric Patterns', brand:'Himachal Handlooms', category:categoryMap['Handloom'], images:[u('1544966503-8e7b6a5f0e46')], price:2800, discount:0, stock:30, state:'Himachal Pradesh', craftType:'Kullu Weaving', isMSME:true, isSustainable:true, isFeatured:false, description:'Hand-woven pure wool shawl from Kullu Valley on pit-looms. Geometric temple-border motifs are unique to each village.', history:'Kullu weaving has been practised in the valleys for centuries.', materials:'Pure wool, vegetable dyes', artisan:'Kullu Valley Handloom Society', specifications:[{key:'Size',value:'100×200 cm'},{key:'Weight',value:'400 grams'}] },
  { name:'Leheriya Tie-Dye Dupatta – Rajasthani', brand:'Anokhi', category:categoryMap['Handloom'], images:[u('1519710164-4b9c3e5ee7be')], price:1400, discount:0, stock:45, state:'Rajasthan', craftType:'Leheriya Tie-Dye', isMSME:true, isSustainable:true, isFeatured:false, description:'Diagonal chevron-stripe resist-dyed dupatta in vibrant Indian colours. The Leheriya technique is unique to Jaipur.', history:'Leheriya means "wave-like" — each cloth is rolled diagonally and tied before dyeing.', materials:'Chiffon georgette, direct fibre dyes', artisan:'Sanganer Dyers Cooperative', specifications:[{key:'Size',value:'100×250 cm'}] },
  { name:'Kantha Quilt – Recycled Silk Sari Patchwork', brand:'Sasha Handicrafts', category:categoryMap['Handloom'], images:[u('1519710164-2c9c3e5ee7be')], price:5200, discount:5, stock:12, state:'West Bengal', craftType:'Kantha Embroidery', isMSME:true, isSustainable:true, isFeatured:false, description:'Recycled silk saris layered and stitched with thousands of tiny running stitches. Every Kantha quilt is absolutely unique.', history:'Kantha is a centuries-old tradition of West Bengal.', materials:'Recycled silk saris, cotton thread', artisan:'Sasha Handicrafts Women Group, Kolkata', specifications:[{key:'Size',value:'Double bed 90×108 inches'}] },
  { name:'Mangalgiri Cotton Shirting – Gold Zari Border', brand:'Fab India', category:categoryMap['Handloom'], images:[u('1519710164-2b9c3e5ee7be')], price:1600, discount:0, stock:50, state:'Andhra Pradesh', craftType:'Mangalgiri Weaving', isMSME:true, isSustainable:true, isFeatured:false, description:'Lightweight Mangalgiri cotton shirting from Guntur with distinctive gold zari selvedge border.', history:'Mangalgiri weaving features the unique Nizam-border technique.', materials:'Organic cotton warp, pure gold zari selvedge', artisan:'Mangalgiri Handloom Weavers Trust', specifications:[{key:'Width',value:'44 inches'},{key:'Sold',value:'Per metre'}] },

  // ─── HANDICRAFTS ────────────────────────────────────────────────────────────
  { name:'Jaipur Blue Pottery Floral Vase', brand:'Jaipur Claycrafts', category:categoryMap['Handicrafts'], images:[u('1610830110-3a56c6c9a85a')], price:1850, discount:0, stock:30, state:'Rajasthan', craftType:'Blue Pottery', isMSME:true, isSustainable:true, isFeatured:true, description:'Hand-painted Jaipur Blue Pottery vase using mineral cobalt oxide on quartz-body ceramic. No clay used — entirely unique to Jaipur.', history:'Jaipur Blue Pottery is a Mughal-era craft using quartz, glass grit and natural gums.', materials:'Quartz powder, glass grit, cobalt glaze', artisan:'Ram Swaroop Pottery Cluster, Sanganer', specifications:[{key:'Height',value:'20 cm'},{key:'Finish',value:'Food-safe glaze'}] },
  { name:'Dhokra Brass Elephant Figurine – Bastar', brand:'Bastar Tribal Art', category:categoryMap['Handicrafts'], images:[u('1602516168-5e1c88e3abe4')], price:2400, discount:0, stock:25, state:'Chhattisgarh', craftType:'Dhokra Lost-Wax Casting', isMSME:true, isSustainable:true, isFeatured:true, description:'4000-year-old lost-wax brass casting technique from Bastar. A wax model is encased in clay and brass poured inside. Each piece is entirely unique.', history:'Dhokra is one of the oldest metal-casting traditions in the world.', materials:'Recycled brass, beeswax, alluvial clay', artisan:'Bastar Dhokra Shilp Kala Cluster', specifications:[{key:'Height',value:'15 cm'},{key:'Weight',value:'320 grams'}] },
  { name:'Channapatna Wooden Toy Set – Eco Lacquer', brand:'Rasoi Crafts', category:categoryMap['Handicrafts'], images:[u('1567016379-6b3b4fe9b5f9')], price:680, discount:0, stock:60, state:'Karnataka', craftType:'Channapatna Wood Carving', isMSME:true, isSustainable:true, isFeatured:false, description:'GI-tagged Channapatna wooden toys hand-turned on traditional lathes using ivory-safe lac dye. 100% safe for children.', history:'Channapatna is called the "Toy-Town" of India near Bengaluru.', materials:'Wrightia tinctoria wood, lac dye', artisan:'Channapatna Heritage Woodcraft Group', specifications:[{key:'Set Contents',value:'10 pieces'},{key:'Age',value:'3+'}] },
  { name:'Madhubani Painting – Village Festival Scene', brand:'Mithila Art Studio', category:categoryMap['Handicrafts'], images:[u('1580933073889-0b4a3971ee80')], price:3200, discount:0, stock:20, state:'Bihar', craftType:'Madhubani Painting', isMSME:true, isSustainable:true, isFeatured:true, description:'Original handmade Madhubani painting on handmade paper using natural pigments. Women artisans depict village festivals in bold two-dimensional lines.', history:'Madhubani painting originated in the Mithila region of Bihar.', materials:'Handmade paper, natural pigments, bamboo pen', artisan:'Mithila Women Artisan Cooperative', specifications:[{key:'Size',value:'45×60 cm'},{key:'Frame',value:'Not included'}] },
  { name:'Warli Tribal Art Canvas – Dance Scene', brand:'Tribal Strokes', category:categoryMap['Handicrafts'], images:[u('1604328698567-40cfce61c2b3')], price:2100, discount:0, stock:18, state:'Maharashtra', craftType:'Warli Tribal Art', isMSME:true, isSustainable:true, isFeatured:false, description:'Hand-painted Warli tribal art on natural canvas using white rice-paste paint. Depicts harvest festival and community gathering scenes.', history:'Warli is practised by the indigenous Warli tribe of northern Maharashtra.', materials:'Organic cotton canvas, rice-paste pigment', artisan:'Warli Tribal Artist Collective, Palghar', specifications:[{key:'Size',value:'40×50 cm'},{key:'Frame',value:'Unframed'}] },
  { name:'Bidriware Decorative Tray – Silver Inlaid', brand:'Deccan Craft House', category:categoryMap['Handicrafts'], images:[u('1568702135-37af5b0f44d6')], price:4500, discount:5, stock:12, state:'Karnataka', craftType:'Bidriware Inlay', isMSME:true, isSustainable:false, isFeatured:false, description:'Zinc-copper alloy tray oxidised jet-black and inlaid with pure silver wire florals. A craft that originated in Bidar during the Bahmani Sultanate.', history:'Bidriware originated in Bidar, Karnataka in the 14th century.', materials:'Zinc-copper alloy, pure silver wire', artisan:'Bidar Craftsmen Cluster', specifications:[{key:'Size',value:'30×20 cm'},{key:'Finish',value:'Oxidised black'}] },
  { name:'Pattachitra Scroll Painting – Lord Jagannath', brand:'Raghurajpur Art', category:categoryMap['Handicrafts'], images:[u('1604328698567-80cfce61c2b3')], price:2800, discount:0, stock:15, state:'Odisha', craftType:'Pattachitra Painting', isMSME:true, isSustainable:true, isFeatured:false, description:'Authentic Pattachitra painting on cotton scroll using stone colours and natural lacquer. Created by hereditary Chitrakaar artists of Raghurajpur.', history:'Pattachitra is an ancient cloth-painting tradition of Odisha.', materials:'Cotton scroll, stone pigments, natural lacquer', artisan:'Raghurajpur Heritage Village Co-op', specifications:[{key:'Size',value:'30×60 cm scroll'}] },
  { name:'Gond Art Painting – Forest Spirit', brand:'Jangarh Art Studio', category:categoryMap['Handicrafts'], images:[u('1604328698567-70cfce61c2b3')], price:4200, discount:0, stock:10, state:'Madhya Pradesh', craftType:'Gond Tribal Art', isMSME:true, isSustainable:true, isFeatured:true, description:'Vibrant Gond tribal painting featuring dotted-and-dashed animal spirits from the Gond tribal imagination. Takes 4–8 weeks.', history:'Gond art from Madhya Pradesh uses a distinctive dot-dash-line visual rhythm.', materials:'Acrylic on canvas', artisan:'Jangarh Singh Shyam Memorial Trust', specifications:[{key:'Size',value:'50×70 cm'},{key:'Frame',value:'Unframed'}] },
  { name:'Kashmiri Paper Mache Lacquer Box', brand:'Suffering Moses Kashmir', category:categoryMap['Handicrafts'], images:[u('1567016379-8b3b4fe9b5f9')], price:2600, discount:0, stock:20, state:'Jammu & Kashmir', craftType:'Paper Mache', isMSME:true, isSustainable:true, isFeatured:false, description:'Hand-painted paper mache box with Persian floral motifs in gold and red. Each box takes 3 days of layering and painting.', history:'Kashmiri paper mache (Kar-e-Qalamdani) has been made for 600+ years.', materials:'Recycled newspaper pulp, natural pigments, lacquer', artisan:'Kashmir Paper Mache Artisan Guild', specifications:[{key:'Size',value:'20×12×8 cm'}] },
  { name:'Kerala Brass Urli Decorative Bowl', brand:'Mohan Lal Sons', category:categoryMap['Handicrafts'], images:[u('1568702135-57af5b0f44d6')], price:3400, discount:0, stock:15, state:'Kerala', craftType:'Brass Casting', isMSME:false, isSustainable:false, isFeatured:false, description:'Traditional Panchaloha bell-metal Urli used in Kerala temples for floating flower offerings. Sand-cast by master craftsmen.', history:'Kerala Urli craft has been tied to temple culture for centuries.', materials:'Panchaloha alloy (5-metal blend)', artisan:'Thrissur Bell Metal Craft Society', specifications:[{key:'Diameter',value:'35 cm'},{key:'Weight',value:'1.2 kg'}] },
  { name:'Terracotta Ganesha from Bishnupur', brand:'Bengal Pottery House', category:categoryMap['Handicrafts'], images:[u('1610830110-5a56c6c9a85a')], price:1200, discount:0, stock:35, state:'West Bengal', craftType:'Terracotta Moulding', isMSME:true, isSustainable:true, isFeatured:false, description:'Hand-moulded terracotta Ganesha inspired by the famous Bishnupur temple panels. Natural red clay, kiln-fired.', history:'Bishnupur terracotta has a 400-year artistic tradition.', materials:'Alluvial terracotta clay, natural kiln', artisan:'Bishnupur Potter Self-Help Group', specifications:[{key:'Height',value:'18 cm'}] },
  { name:'Rogan Art Painted Cushion Cover', brand:'Kutch Craft Village', category:categoryMap['Handicrafts'], images:[u('1581623895-cbedb8e0d479')], price:1600, discount:0, stock:25, state:'Gujarat', craftType:'Rogan Art', isMSME:true, isSustainable:true, isFeatured:false, description:'Rogan art uses boiled castor-oil paint applied on cloth using a metal rod. Only one family in Kutch preserves this 300-year-old technique.', history:'Rogan art is one of India\'s most endangered crafts.', materials:'Castor oil paint, handwoven cotton', artisan:'Khatri Family, Nirona Village, Kutch', specifications:[{key:'Size',value:'45×45 cm'}] },
  { name:'Leather Puppet – Tholu Bommalata, Andhra', brand:'Nimmalakunta Crafts', category:categoryMap['Handicrafts'], images:[u('1566073506-a87843c50a83')], price:1950, discount:0, stock:18, state:'Andhra Pradesh', craftType:'Shadow Puppetry', isMSME:true, isSustainable:true, isFeatured:false, description:'Translucent goat-leather shadow puppet painted with bold primary colours. Each puppet requires 3 days of craftwork.', history:'Tholu Bommalata is a 2000-year-old shadow puppet tradition.', materials:'Vegetable-tanned goat leather, natural dyes', artisan:'Nimmalakunta Leather Craft Centre', specifications:[{key:'Size',value:'40×50 cm'}] },
  { name:'Dhokra Brass Peacock Wall Art', brand:'Orissa Crafts Org', category:categoryMap['Handicrafts'], images:[u('1545558935-0f6c00e4d03e')], price:3800, discount:0, stock:12, state:'Odisha', craftType:'Dhokra Casting', isMSME:true, isSustainable:true, isFeatured:false, description:'Bell-metal wall panel depicting a peacock in full display, cast using Odisha\'s traditional lost-wax process.', history:'Odisha bell-metal Dhokra is distinct from Bastar\'s brass Dhokra.', materials:'Bell metal alloy (brass + tin)', artisan:'Dhenkanal Bell Metal Craft Society', specifications:[{key:'Size',value:'40×50 cm wall panel'}] },
  { name:'Kondapalli Wooden Doll Set – GI Tagged', brand:'Andhra Craft Board', category:categoryMap['Handicrafts'], images:[u('1604328698567-90cfce61c2b3')], price:1400, discount:10, stock:30, state:'Andhra Pradesh', craftType:'Kondapalli Toy Making', isMSME:true, isSustainable:true, isFeatured:false, description:'GI-tagged Kondapalli toys carved from soft Tella Poniki wood and painted with natural dyes. A 400-year-old toy-making tradition.', history:'Kondapalli toys were patronised by the Golconda sultans.', materials:'Tella Poniki wood, natural dyes', artisan:'Kondapalli Toy Makers Society, Andhra Pradesh', specifications:[{key:'Set',value:'5 figurines'},{key:'Age',value:'3+'}] },

  // ─── FASHION ────────────────────────────────────────────────────────────────
  { name:'Bandhani Lehenga Set – Rajasthani Tie-Dye', brand:'Kalki Fashion', category:categoryMap['Fashion'], images:[u('1610030169-d56d7a22a86e')], price:12500, discount:10, stock:15, state:'Rajasthan', craftType:'Bandhani Tie-Dye', isMSME:false, isSustainable:false, isFeatured:true, description:'Traditional Rajasthani Bandhani tie-dye lehenga set with thousands of tiny tied dots creating floral patterns.', history:'Bandhani is an ancient tie-dye craft of Rajasthan and Gujarat.', materials:'Pure cotton, natural tie-dye, gota ribbon', artisan:'Jaipur Artisan Guild', specifications:[{key:'Sizes',value:'XS-XXL'},{key:'Occasion',value:'Weddings, festivals'}] },
  { name:'Lucknowi Chikankari Kurta – Hand Embroidered', brand:'Aza Fashions', category:categoryMap['Fashion'], images:[u('1594938298608-2e9d7b8b3e4a')], price:3200, discount:5, stock:30, state:'Uttar Pradesh', craftType:'Chikankari Embroidery', isMSME:true, isSustainable:true, isFeatured:true, description:'400-year-old white-thread embroidery technique from Lucknow. Artisans use 36 distinct stitches to create shadow-work floral patterns.', history:'Chikankari was introduced to Lucknow by the Mughal court.', materials:'Fine muslin, white cotton floss', artisan:'Lucknow Chikankari Artisan Group', specifications:[{key:'Sizes',value:'S/M/L/XL'},{key:'Occasion',value:'Casual/Formal'}] },
  { name:'Kalamkari Cotton Kurta – Hand-Drawn Floral', brand:'Dhrama Designs', category:categoryMap['Fashion'], images:[u('1594938298608-7a1f9c2d8e3a')], price:1650, discount:0, stock:45, state:'Andhra Pradesh', craftType:'Kalamkari Printing', isMSME:true, isSustainable:true, isFeatured:false, description:'Kalamkari "pen work" uses a bamboo pen and tamarind dyes to hand-draw mythological narratives on cotton.', history:'Kalamkari is one of the oldest fabric art forms in India.', materials:'Organic cotton, tamarind dyes', artisan:'Machilipatnam Kalamkari Centre', specifications:[{key:'Sizes',value:'S-XXL'},{key:'Wash',value:'Cold hand wash'}] },
  { name:'Paithani Silk Saree – Peacock Pallav', brand:'Ranka Jewellers', category:categoryMap['Fashion'], images:[u('1583241800-6e6e4bfde2f2')], price:22000, discount:5, stock:8, state:'Maharashtra', craftType:'Paithani Weaving', isMSME:false, isSustainable:false, isFeatured:true, description:'Royal Paithani saree of Maharashtra woven with the interlocked tapestry technique. The peacock pallav motif requires months of skilled weaving.', history:'Paithani was the royal silk of the Peshwas of Pune.', materials:'Pure silk warp, zari weft', artisan:'Yeola Handloom Weavers Co-op', specifications:[{key:'Length',value:'5.5m'},{key:'Zari',value:'Real silver'}] },
  { name:'Woollen Stole – Kullu Valley Handloom', brand:'Himachal Handlooms', category:categoryMap['Fashion'], images:[u('1544966503-7f56c85f1f4e')], price:2800, discount:0, stock:25, state:'Himachal Pradesh', craftType:'Kullu Weaving', isMSME:true, isSustainable:true, isFeatured:false, description:'Pure wool stole woven on pit-looms in the Kullu Valley with distinctive geometric temple-border designs.', history:'Kullu Valley weaving has a century-old tradition.', materials:'Pure Himalayan wool', artisan:'Kullu Valley Handloom Society', specifications:[{key:'Size',value:'70×180 cm'}] },
  { name:'Men\'s Bandhgala Suit – Jodhpur Style', brand:'Manyavar', category:categoryMap['Fashion'], images:[u('1594938298608-ec58f5d3e4cb')], price:8500, discount:15, stock:20, state:'Rajasthan', craftType:'Traditional Tailoring', isMSME:false, isSustainable:false, isFeatured:false, description:'Regal Jodhpur-style Bandhgala suit in premium wool-blend. Traditional fitted silhouette for weddings and formal occasions.', history:'The Bandhgala (closed-collar) suit was popularised by Jodhpur rulers.', materials:'Premium wool-silk blend, silk lining', artisan:'Manyavar Heritage Collection', specifications:[{key:'Sizes',value:'36-44 inches'},{key:'Includes',value:'Coat + trousers'}] },
  { name:'Assam Muga Silk Scarf – Natural Gold Sheen', brand:'Silkworm Assam', category:categoryMap['Fashion'], images:[u('1519710164-3c9c3e5ee7be')], price:4200, discount:0, stock:22, state:'Assam', craftType:'Muga Silk Weaving', isMSME:true, isSustainable:true, isFeatured:false, description:'Lightweight Muga silk scarf that shines brighter with every wash. Woven on traditional Assamese pit-looms.', history:'Muga silk is exclusive to Assam, India.', materials:'Wild Muga silk cocoons', artisan:'Sualkuchi Weaving Cluster, Assam', specifications:[{key:'Size',value:'50×180 cm'}] },
  { name:'Ikat Silk Saree – Pochampally Double Ikat', brand:'Ekaya Banaras', category:categoryMap['Fashion'], images:[u('1585386959-a4a9b3b4b8fc')], price:7200, discount:8, stock:18, state:'Telangana', craftType:'Pochampally Ikat', isMSME:true, isSustainable:true, isFeatured:false, description:'GI-tagged Pochampally double-ikat silk saree with mirror-symmetric geometric patterns. Both warp and weft are resist-dyed.', history:'Pochampally Ikat is UNESCO-recognised Intangible Cultural Heritage.', materials:'Pure mulberry silk, chemical-free dyes', artisan:'Bhoodan Pochampally Handloom Society', specifications:[{key:'Length',value:'5.5m'},{key:'Blouse',value:'Included'}] },
  { name:'Anarkali Suit – Banarasi Brocade', brand:'Meena Bazaar', category:categoryMap['Fashion'], images:[u('1610030169-4d0c0ef6d26d')], price:6500, discount:12, stock:15, state:'Uttar Pradesh', craftType:'Banarasi Brocade', isMSME:true, isSustainable:false, isFeatured:false, description:'Elegant Anarkali style floor-length suit in Banarasi silk brocade with intricate floral zari weave. Ideal for festivals and weddings.', history:'Banarasi brocade weaving has been practised in Varanasi for 500+ years.', materials:'Banarasi silk brocade, cotton lining', artisan:'Varanasi Silk Brocade Cooperative', specifications:[{key:'Sizes',value:'XS-XXL'},{key:'Dupatta',value:'Included'}] },
  { name:'Nehru Jacket – Handloom Khadi', brand:'Fab India', category:categoryMap['Fashion'], images:[u('1594938298608-ec58f5d3e4cb')], price:2800, discount:0, stock:35, state:'Gujarat', craftType:'Khadi Weaving', isMSME:true, isSustainable:true, isFeatured:false, description:'Classic Nehru jacket in hand-spun khadi fabric. Perfect for both formal and casual wear. KVIC certified.', history:'The Nehru jacket became internationally famous after Jawaharlal Nehru.', materials:'100% hand-spun khadi cotton', artisan:'KVIC, Gujarat', specifications:[{key:'Sizes',value:'S-XXL'},{key:'Pockets',value:'2 front, 1 chest'}] },
  { name:'Kerala Kasavu Saree – Golden Zari Border', brand:'Jayalakshmi Silks', category:categoryMap['Fashion'], images:[u('1610030169-6e6e4bfde2f2')], price:3500, discount:0, stock:25, state:'Kerala', craftType:'Kerala Handloom', isMSME:true, isSustainable:false, isFeatured:false, description:'Traditional Kerala Kasavu saree in cream cotton with broad gold zari border. Worn at Onam, Vishu and weddings.', history:'Kasavu weaving is Kerala\'s oldest textile tradition.', materials:'Fine cotton, pure gold zari border', artisan:'Balaramapuram Handloom Society, Kerala', specifications:[{key:'Length',value:'5.5m'},{key:'Occasion',value:'Onam, Vishu, weddings'}] },
  { name:'Rajasthani Block Print Kurta Set', brand:'Anokhi', category:categoryMap['Fashion'], images:[u('1594938298608-7a1f9c2d8e3a')], price:2200, discount:5, stock:40, state:'Rajasthan', craftType:'Block Printing', isMSME:true, isSustainable:true, isFeatured:false, description:'Hand block-printed kurta set using wooden stamps on pure cotton. Natural vegetable dyes in earthy Rajasthani colour palette.', history:'Block printing on cotton has been practised in Rajasthan for 500+ years.', materials:'100% cotton, vegetable dyes', artisan:'Bagru Block Print Artisan Guild', specifications:[{key:'Set',value:'Kurta + Palazzo'},{key:'Sizes',value:'XS-XL'}] },
  { name:'Tant Cotton Saree – Bengal Handloom', brand:'Tantuja', category:categoryMap['Fashion'], images:[u('1583241800-4e4e2bfde2f2')], price:1800, discount:0, stock:35, state:'West Bengal', craftType:'Tant Weaving', isMSME:true, isSustainable:true, isFeatured:false, description:'Lightweight Tant cotton saree from West Bengal with delicate woven border. The most popular everyday saree across Bengal.', history:'Tant weaving is the quintessential handloom of West Bengal.', materials:'Fine cotton yarn, natural sizing', artisan:'Nadia District Handloom Society', specifications:[{key:'Length',value:'5.5m'},{key:'Width',value:'44 inches'}] },
  { name:'Designer Salwar Kameez – Hand-Woven Cotton', brand:'Good Earth', category:categoryMap['Fashion'], images:[u('1610030169-d56d7a22a86e')], price:4800, discount:10, stock:20, state:'Rajasthan', craftType:'Hand Weaving', isMSME:false, isSustainable:true, isFeatured:false, description:'Premium designer salwar kameez in handwoven cotton with subtle texture. Comes with dupatta. Contemporary Indian fashion.', history:'Good Earth combines Indian craft traditions with modern design.', materials:'Handwoven cotton, natural dyes, silk dupatta', artisan:'Good Earth Artisan Partners', specifications:[{key:'Sizes',value:'XS-XL'},{key:'Set',value:'Kurta + Salwar + Dupatta'}] },

  // ─── JEWELLERY ────────────────────────────────────────────────────────────
  { name:'Kundan Polki Necklace Set – Bridal', brand:'Amrapali Jaipur', category:categoryMap['Jewellery'], images:[u('1542038906-8800c4d7c8b6')], price:24500, discount:5, stock:8, state:'Rajasthan', craftType:'Kundan Jewellery', isMSME:false, isSustainable:false, isFeatured:true, description:'22kt gold Kundan necklace set with uncut diamond Polki stones. Each stone is individually set in molten gold using lac filling.', history:'Kundan jewellery originated in the Mughal court of Rajasthan.', materials:'22kt gold foil, Polki diamond, lac', artisan:'Jaipur Gemstone Jewellers Cluster', specifications:[{key:'Gold',value:'22kt'},{key:'Set',value:'Necklace + Earrings + Maang Tikka'}] },
  { name:'Silver Filigree Pendant – Cuttack Craft', brand:'Odisha Craft', category:categoryMap['Jewellery'], images:[u('1542038906-0800c4d7c8b6')], price:4200, discount:0, stock:20, state:'Odisha', craftType:'Silver Filigree', isMSME:true, isSustainable:false, isFeatured:true, description:'99.9% pure silver wire twisted into intricate lace-like patterns. An Cuttack Tarakasi pendant can contain 50+ metres of wire.', history:'Tarakasi silver filigree is Cuttack\'s most famous craft.', materials:'99.9% pure silver wire, no solder', artisan:'Cuttack Silver Filigree Association', specifications:[{key:'Silver',value:'99.9% pure'},{key:'Chain',value:'Included'}] },
  { name:'Meenakari Enamel Bangles Set – Gold Plated', brand:'Amrapali', category:categoryMap['Jewellery'], images:[u('1542038906-9800c4d7c8b6')], price:3200, discount:0, stock:25, state:'Rajasthan', craftType:'Meenakari Enamelwork', isMSME:true, isSustainable:false, isFeatured:false, description:'Kiln-fired glass enamels in vibrant colours set into engraved gold-plated brass channels. Traditional Jaipur Meenakari technique.', history:'Meenakari enamel art was introduced to Amber court in the 16th century.', materials:'Gold-plated brass, kiln-fired enamel', artisan:'Jaipur Meenakari Artisan Cluster', specifications:[{key:'Size',value:'2.4 inch diameter'},{key:'Set',value:'6 bangles'}] },
  { name:'Temple Gold Earrings – South Indian', brand:'Tanishq', category:categoryMap['Jewellery'], images:[u('1535893673-4e1c54d2e04c')], price:8500, discount:0, stock:12, state:'Tamil Nadu', craftType:'Temple Jewellery', isMSME:false, isSustainable:false, isFeatured:true, description:'22kt BIS-hallmarked gold temple earrings with ruby and emerald accents. Originally made to adorn temple idols and bharatanatyam dancers.', history:'South Indian temple jewellery has a 2000-year tradition.', materials:'22kt BIS-hallmarked gold, ruby, emerald', artisan:'GRT Certified Goldsmiths', specifications:[{key:'Gold',value:'22kt BIS Hallmarked'},{key:'Weight',value:'8 grams'}] },
  { name:'Lac Bangle Set – Rajasthani (12 bangles)', brand:'Shree Bangles', category:categoryMap['Jewellery'], images:[u('1535893673-5e1c54d2e04c')], price:950, discount:0, stock:50, state:'Rajasthan', craftType:'Lacquerware', isMSME:true, isSustainable:true, isFeatured:false, description:'Natural lac resin bangles embedded with glass stones and mirror inlay. A traditional Rajasthani craft practised for centuries.', history:'Lac bangle making is one of Rajasthan\'s oldest cottage industries.', materials:'Natural lac resin, glass stones, mirror inlay', artisan:'Jaipur Lac Artisan Co-op', specifications:[{key:'Size',value:'2.4 / 2.6 / 2.8 inch'},{key:'Set',value:'12 bangles'}] },
  { name:'Oxidised Silver Tribal Choker Necklace', brand:'Silvesto India', category:categoryMap['Jewellery'], images:[u('1535893673-3e1c54d2e04c')], price:1800, discount:0, stock:30, state:'Rajasthan', craftType:'Oxidised Silver', isMSME:true, isSustainable:false, isFeatured:false, description:'92.5 sterling silver choker with oxidised finish inspired by Bhil and Gond tribal jewellery traditions.', history:'Tribal silver jewellery of Rajasthan uses centuries-old techniques.', materials:'92.5 sterling silver, chemical oxidation', artisan:'Jaipur Silver Artisan Guild', specifications:[{key:'Silver',value:'92.5 Sterling'},{key:'Length',value:'Adjustable 14–18 inches'}] },
  { name:'Navratna Sterling Silver Pendant', brand:'Ratna Sagar', category:categoryMap['Jewellery'], images:[u('1535893673-6e1c54d2e04c')], price:5400, discount:5, stock:15, state:'Uttar Pradesh', craftType:'Gemstone Setting', isMSME:true, isSustainable:false, isFeatured:false, description:'Nine Vedic gemstones representing the nine planets set in 92.5 sterling silver. Each stone is certified for quality and authenticity.', history:'Navratna jewellery is a classical Ayurvedic astrological tradition.', materials:'92.5 sterling silver, 9 certified gemstones', artisan:'Jaipur Gemstone Jewellers Cluster', specifications:[{key:'Silver',value:'92.5 Sterling'},{key:'Chain',value:'Included'}] },
  { name:'Pearl Haar Necklace – Hyderabad Double Strand', brand:'Mangatrai', category:categoryMap['Jewellery'], images:[u('1535893673-7e1c54d2e04c')], price:12800, discount:0, stock:8, state:'Telangana', craftType:'Pearl Stringing', isMSME:false, isSustainable:false, isFeatured:false, description:'Double-strand freshwater pearl necklace knotted on silk thread with 18kt gold clasp. Hyderabad has been the world pearl capital since the Nizam era.', history:'Hyderabad pearl trading has a 400-year-old royal heritage.', materials:'Freshwater pearls, silk knotted thread, 18kt gold clasp', artisan:'Hyderabad Pearl Artisan Federation', specifications:[{key:'Gold Clasp',value:'18kt'},{key:'Length',value:'18 inches'}] },
  { name:'Jhumka Earrings – Antique Brass with Mirror', brand:'Zevar by Ritu', category:categoryMap['Jewellery'], images:[u('1535893673-8e1c54d2e04c')], price:1100, discount:0, stock:40, state:'Gujarat', craftType:'Metal Jewellery', isMSME:true, isSustainable:false, isFeatured:false, description:'Traditional Gujarati Jhumka bell-drop earrings with handset mirror-glass that catch light during Garba dance.', history:'Jhumka earrings have been worn in India since the 10th century.', materials:'Antique brass, handset mirror glass', artisan:'Rajkot Jewellery Artisan Guild', specifications:[{key:'Length',value:'5 cm drop'},{key:'Weight',value:'12 grams per pair'}] },
  { name:'Bidri Silver-Inlaid Ring', brand:'Deccan Craft House', category:categoryMap['Jewellery'], images:[u('1542038906-5800c4d7c8b6')], price:2200, discount:0, stock:20, state:'Karnataka', craftType:'Bidriware Inlay', isMSME:true, isSustainable:false, isFeatured:false, description:'Pure silver wire inlaid into oxidised zinc-copper alloy ring. The jet-black finish comes from sal ammoniac soil of Bidar Fort. No two rings are identical.', history:'Bidri craft originated in Bidar, Karnataka, in the 14th century.', materials:'Zinc-copper alloy, pure silver inlay', artisan:'Bidar Craftsmen Cluster', specifications:[{key:'Sizes',value:'5-12 US ring size'}] },
  { name:'Dokra Choker – Tribal Bell Motif', brand:'Bastar Craft', category:categoryMap['Jewellery'], images:[u('1542038906-1800c4d7c8b6')], price:1650, discount:0, stock:25, state:'Chhattisgarh', craftType:'Dhokra Casting', isMSME:true, isSustainable:true, isFeatured:false, description:'Lost-wax cast brass bell-motif choker necklace from Bastar tribal tradition. Each bell is individually cast and carries totemic significance.', history:'Dhokra jewellery is worn by Gondi and Muria tribal communities.', materials:'Recycled brass, traditional bell alloy', artisan:'Bastar Tribal Artisan Federation', specifications:[{key:'Length',value:'Adjustable 14–18 inches'}] },
  { name:'Silver Payal Anklet Pair – Ghungroo', brand:'Zaveri Bazaar', category:categoryMap['Jewellery'], images:[u('1542038906-4800c4d7c8b6')], price:3800, discount:0, stock:18, state:'Maharashtra', craftType:'Silver Jewellery', isMSME:true, isSustainable:false, isFeatured:false, description:'92.5 sterling silver anklets with hollow ghungroo bells. Essential for bharatanatyam and Kathak dance. Each bell attached individually.', history:'Ghungroo anklets are essential for classical Indian dance.', materials:'92.5 sterling silver, hollow silver ghungroos', artisan:'Zaveri Bazaar Silversmith Community', specifications:[{key:'Silver',value:'92.5 Sterling'},{key:'Bells',value:'25 per pair'}] },
  { name:'Kundan Maang Tikka – Forehead Jewel', brand:'Amrapali Jaipur', category:categoryMap['Jewellery'], images:[u('1535893673-9e1c54d2e04c')], price:4200, discount:0, stock:12, state:'Rajasthan', craftType:'Kundan Jewellery', isMSME:false, isSustainable:false, isFeatured:false, description:'Bridal Maang Tikka with Kundan-set Polki diamond and gemstones in 22kt gold foil. A centrepiece for any bridal look.', history:'The Maang Tikka is a traditional Rajasthani bridal ornament.', materials:'22kt gold foil, Polki diamond, colour gemstones', artisan:'Jaipur Gemstone Jewellers Cluster', specifications:[{key:'Gold',value:'22kt foil'},{key:'Occasion',value:'Bridal'}] },
  { name:'Tribal Dhokra Bracelet – Horn & Brass', brand:'Bastar Craft', category:categoryMap['Jewellery'], images:[u('1542038906-3800c4d7c8b6')], price:780, discount:0, stock:35, state:'Chhattisgarh', craftType:'Dhokra Casting', isMSME:true, isSustainable:true, isFeatured:false, description:'Dhokra brass and buffalo-horn bracelet from Bastar. The geometric patterns carry totemic significance for Gondi communities.', history:'Bastar tribal jewellery uses brass casting and buffalo-horn elements.', materials:'Lost-wax brass, polished buffalo horn', artisan:'Bastar Tribal Artisan Federation', specifications:[{key:'Size',value:'Adjustable'},{key:'Width',value:'2 cm'}] },

  // ─── HOME DECOR ──────────────────────────────────────────────────────────
  { name:'Handwoven Jute Rug – Natural 5×8 ft', brand:'EcoWeave India', category:categoryMap['Home Decor'], images:[u('1567016379-5b3b4fe9b5f9')], price:5400, discount:10, stock:15, state:'West Bengal', craftType:'Jute Weaving', isMSME:true, isSustainable:true, isFeatured:true, description:'100% organic jute hand-woven rug from West Bengal. Biodegradable and insect-resistant. Lasts 15+ years with proper care.', history:'West Bengal produces 75% of the world\'s jute.', materials:'100% organic jute fibre, vegetable dyes', artisan:'Howrah Weaving Self-Help Group', specifications:[{key:'Size',value:"5'×8'"},{key:'Weight',value:'3.5 kg'}] },
  { name:'Kashmiri Walnut Wood Carved Bowl', brand:'Kashmir Handicraft Emporium', category:categoryMap['Home Decor'], images:[u('1568702135-67af5b0f44d6')], price:6200, discount:5, stock:10, state:'Jammu & Kashmir', craftType:'Walnut Wood Carving', isMSME:true, isSustainable:true, isFeatured:true, description:'Intricately carved Kashmiri walnut bowl with chinar leaf and Mughal floral arabesque patterns. Each piece takes 2 weeks.', history:'Kashmiri walnut carving dates to the 15th century.', materials:'Aged Kashmiri walnut wood, natural lacquer', artisan:'Kashmir Handicraft Emporium, Srinagar', specifications:[{key:'Diameter',value:'25 cm'},{key:'Depth',value:'10 cm'}] },
  { name:'Brass Diya Gift Set of 12 – Diwali', brand:'Brass Bazar India', category:categoryMap['Home Decor'], images:[u('1569937756-8c94c4e4b2af')], price:1200, discount:0, stock:50, state:'Rajasthan', craftType:'Brass Casting', isMSME:true, isSustainable:true, isFeatured:true, description:'Hand-polished cast brass diyas for Diwali. Polished with tamarind paste for golden finish. Sold as a set of 12.', history:'Moradabad is India\'s "Brass Capital" for decorative castings.', materials:'Cast brass, hand-polished Moradabad finish', artisan:'Moradabad Brass Craft Cluster', specifications:[{key:'Set',value:'12 diyas'},{key:'Diameter',value:'6 cm each'}] },
  { name:'Copper Hammered Water Jug – 1.5L', brand:'Vedic Vatica', category:categoryMap['Home Decor'], images:[u('1568702135-77af5b0f44d6')], price:1800, discount:0, stock:35, state:'Rajasthan', craftType:'Copper Craft', isMSME:true, isSustainable:true, isFeatured:false, description:'Food-grade pure copper jug, hand-hammered by Rajasthani metalworkers. Ayurveda recommends storing water in copper for health benefits.', history:'Copper vessel craft has been practised in Rajasthan for centuries.', materials:'99% pure food-grade copper, lead-free', artisan:'Jaipur Copper Craft Cluster', specifications:[{key:'Capacity',value:'1.5 Litres'},{key:'Copper',value:'99% food grade'}] },
  { name:'Madhubani Painted Wooden Coaster Set of 6', brand:'Mithila Art', category:categoryMap['Home Decor'], images:[u('1580933073889-1b4a3971ee80')], price:1400, discount:0, stock:40, state:'Bihar', craftType:'Madhubani Painting', isMSME:true, isSustainable:true, isFeatured:false, description:'Traditional Madhubani fish, lotus and peacock motifs hand-painted on round teak coasters. Food-safe acrylic seal.', history:'Madhubani art originated in the Mithila region of Bihar.', materials:'Teak wood disc, natural pigments, acrylic seal', artisan:'Mithila Women Artisan Cooperative', specifications:[{key:'Diameter',value:'10 cm'},{key:'Set',value:'6 coasters'}] },
  { name:'Phulkari Embroidered Cushion Cover Set of 2', brand:'Amrapali Home', category:categoryMap['Home Decor'], images:[u('1581623895-dbedb8e0d479')], price:1600, discount:5, stock:30, state:'Punjab', craftType:'Phulkari Embroidery', isMSME:true, isSustainable:true, isFeatured:false, description:'Phulkari "flower work" embroidered cushion covers adapting Punjab\'s traditional bold geometric floral patterns for contemporary homes.', history:'Phulkari embroidery is a 500-year-old tradition of Punjab.', materials:'Cotton base, pure silk embroidery thread', artisan:'Punjab Phulkari Artisan Collective', specifications:[{key:'Size',value:'45×45 cm'},{key:'Set',value:'2 covers'}] },
  { name:'Bamboo Lampshade – Assamese Weave', brand:'Crafts Council NE', category:categoryMap['Home Decor'], images:[u('1545558935-5f6c00e4d03e')], price:2400, discount:0, stock:22, state:'Assam', craftType:'Bamboo Weaving', isMSME:true, isSustainable:true, isFeatured:false, description:'Hand-woven Assamese bamboo lampshade that filters warm light through geometric woven grids. Eco-friendly and biodegradable.', history:'Bamboo grows naturally in Assam without pesticides.', materials:'Local Himalayan bamboo, natural varnish', artisan:'Northeast India Bamboo Craft Circle', specifications:[{key:'Diameter',value:'30 cm'},{key:'Height',value:'25 cm'},{key:'Fit',value:'E27 standard bulb'}] },
  { name:'Pipli Applique Hanging Lamp', brand:'Pipli Craft House', category:categoryMap['Home Decor'], images:[u('1545558935-3f6c00e4d03e')], price:1800, discount:0, stock:28, state:'Odisha', craftType:'Pipli Applique', isMSME:true, isSustainable:true, isFeatured:false, description:'Brightly coloured fabric applique lamp from Pipli village near Puri. The floral cut-out work creates colourful shadow patterns when lit.', history:'Pipli is a craft village where every family practises applique art.', materials:'Cotton fabric applique, brass fittings', artisan:'Pipli Artisan Village Cooperative', specifications:[{key:'Diameter',value:'25 cm'},{key:'Height',value:'20 cm'}] },
  { name:'Dhurrie Flatweave Rug – Rajasthani Stripe', brand:'Fabindia', category:categoryMap['Home Decor'], images:[u('1581623895-ebedb8e0d479')], price:4800, discount:8, stock:15, state:'Rajasthan', craftType:'Flatweave Dhurrie', isMSME:true, isSustainable:true, isFeatured:false, description:'Traditional Rajasthani flatweave dhurrie with bold geometric stripes. Woven on frame looms using recycled cotton.', history:'Salawas village in Jodhpur district specialises in dhurrie weaving.', materials:'Recycled cotton, vegetable dyes, jute warp', artisan:'Salawas Dhurrie Weaver Community', specifications:[{key:'Size',value:"4'×6'"},{key:'Thickness',value:'8mm'}] },
  { name:'Warli Painted Wooden Side Table', brand:'Wooden Street', category:categoryMap['Home Decor'], images:[u('1521783988-7e7d0a3e2b3b')], price:8500, discount:10, stock:8, state:'Maharashtra', craftType:'Warli Tribal Art', isMSME:true, isSustainable:true, isFeatured:false, description:'Solid mango wood side table hand-painted with white Warli tribal motifs. Contemporary furniture meets tribal art tradition.', history:'Warli art is practised by the indigenous Warli tribe.', materials:'Solid mango wood, non-toxic eco-paint', artisan:'Warli Artisan Studio, Palghar', specifications:[{key:'Dimensions',value:'45×45×50 cm (H)'},{key:'Weight capacity',value:'20 kg'}] },
  { name:'Kalamkari Printed Table Runner – 180cm', brand:'Anokhi', category:categoryMap['Home Decor'], images:[u('1567016379-7b3b4fe9b5f9')], price:1100, discount:0, stock:35, state:'Andhra Pradesh', craftType:'Kalamkari Printing', isMSME:true, isSustainable:true, isFeatured:false, description:'Srikalahasti-style Kalamkari table runner using iron-acetate black, pomegranate yellow and indigo blue dyes. Temple story motifs.', history:'Srikalahasti Kalamkari uses a bamboo pen (kalam) for drawing.', materials:'Organic cotton, natural dyes, tamarind mordant', artisan:'Srikalahasti Kalamkari Artisan Centre', specifications:[{key:'Size',value:'35×180 cm'}] },
  { name:'Channapatna Wooden Bowl – Lacquer Finished', brand:'Channapatna Crafts', category:categoryMap['Home Decor'], images:[u('1567016379-6b3b4fe9b5f9')], price:890, discount:0, stock:45, state:'Karnataka', craftType:'Channapatna Wood Carving', isMSME:true, isSustainable:true, isFeatured:false, description:'Hand-turned Channapatna wooden bowl in vibrant lac colours. Food-safe and lightweight.', history:'Channapatna woodcraft is GI-tagged and 200+ years old.', materials:'Wrightia tinctoria wood, lac dye', artisan:'Channapatna Heritage Woodcraft Group', specifications:[{key:'Diameter',value:'20 cm'},{key:'Food-safe',value:'Yes'}] },
  { name:'Neem Wood Salt & Pepper Set', brand:'Ariro Naturals', category:categoryMap['Home Decor'], images:[u('1521783988-8e7b6a5f0e46')], price:680, discount:0, stock:50, state:'Tamil Nadu', craftType:'Wood Carving', isMSME:true, isSustainable:true, isFeatured:false, description:'Neem wood salt & pepper shakers, naturally antimicrobial and insect-repellent. Finished with food-safe sesame oil.', history:'Neem is considered sacred and therapeutic in Ayurvedic tradition.', materials:'Organic neem wood, food-safe sesame oil', artisan:'Ariro Toy Crafts, Chennai', specifications:[{key:'Height',value:'8 cm'},{key:'Material',value:'Organic neem wood'}] },
  { name:'Brass Incense Holder – Lotus Design', brand:'Artisanal India', category:categoryMap['Home Decor'], images:[u('1569937756-9c94c4e4b2af')], price:850, discount:0, stock:60, state:'Rajasthan', craftType:'Brass Casting', isMSME:true, isSustainable:true, isFeatured:false, description:'Hand-cast lotus-shaped brass incense holder for sticks and cones. Sand-cast and hand-polished to a warm golden finish.', history:'Brass craftsmanship from Jaipur is known for its intricate sand casting.', materials:'Cast brass', artisan:'Jaipur Brass Artisan Guild', specifications:[{key:'Length',value:'25 cm'},{key:'Compatible',value:'Sticks and cone incense'}] },
  { name:'Wooden Ganesha Wall Panel – Teak', brand:'The Elephant Company', category:categoryMap['Home Decor'], images:[u('1545558935-7f6c00e4d03e')], price:5600, discount:5, stock:10, state:'Kerala', craftType:'Wood Carving', isMSME:false, isSustainable:false, isFeatured:false, description:'Large Kerala-style teak wood wall panel with three-dimensional Ganesha relief. Inspired by traditional temple door carvings.', history:'Kerala\'s wood carving tradition for temples is over 1000 years old.', materials:'Sustainably-sourced teak, natural lacquer', artisan:'Thrissur Wood Carving Society', specifications:[{key:'Size',value:'60×90 cm'},{key:'Depth',value:'5 cm relief'}] },

  // ─── AYURVEDA ─────────────────────────────────────────────────────────────
  { name:'Eladi Hydrating Ayurvedic Facial Cream', brand:'Forest Essentials', category:categoryMap['Ayurveda'], images:[u('1556228578-8c53b12c5b47')], price:2450, discount:0, stock:40, state:'Kerala', craftType:'Ayurvedic Formulation', isMSME:false, isSustainable:true, isFeatured:true, description:'Cold-processed facial cream based on Ashtanga Hridaya formulas. Contains pearl powder, cardamom, and saffron for luminous skin.', history:'The Eladi formula is documented in classical Ayurvedic texts.', materials:'Cold-pressed coconut oil, saffron, cardamom, pearl powder', artisan:'Forest Essentials Heritage Labs', specifications:[{key:'Volume',value:'50g'},{key:'Skin Type',value:'All skin types'}] },
  { name:'Pure Kumkumadi Tailam Face Serum', brand:'Vaidyaratnam', category:categoryMap['Ayurveda'], images:[u('1526570207-6b8e3bd3e5aa5')], price:3200, discount:5, stock:30, state:'Kerala', craftType:'Classical Oil Preparation', isMSME:false, isSustainable:true, isFeatured:true, description:'The Ayurvedic gold standard for skin radiance. 16-day slow infusion of saffron, lotus stamens and sandalwood in sesame oil.', history:'Kumkumadi Tailam is documented in Ashtanga Hridayam, 7th century CE.', materials:'Saffron, lotus stamens, sandalwood, sesame oil', artisan:'Vaidyaratnam Heritage Laboratory, Ollur', specifications:[{key:'Volume',value:'12ml'},{key:'Use',value:'3-5 drops nightly'}] },
  { name:'Kama Ayurveda Pure Rose Water Toner', brand:'Kama Ayurveda', category:categoryMap['Ayurveda'], images:[u('1526570207-7b8e3bd3e5aa5')], price:895, discount:0, stock:60, state:'Rajasthan', craftType:'Steam Distillation', isMSME:false, isSustainable:true, isFeatured:false, description:'Traditional deg-bhapka steam distillation from 400-year-old Pushkar rose farms. Prized by Mughal perfumers.', history:'Kannauj and Pushkar have produced rose water for 400 years.', materials:'Damask roses, purified mountain spring water', artisan:'Kannauj Attar Distillery Collective', specifications:[{key:'Volume',value:'200ml'},{key:'Preservative',value:'None'}] },
  { name:'Ashwagandha KSM-66 Capsules – 60 count', brand:'Himalaya Wellness', category:categoryMap['Ayurveda'], images:[u('1471193565-6b73dc8e3e01')], price:680, discount:10, stock:80, state:'Uttarakhand', craftType:'Herbal Extraction', isMSME:false, isSustainable:true, isFeatured:false, description:'Full-spectrum Ashwagandha root extract (KSM-66). The cornerstone adaptogen of Ayurvedic medicine for stress and vitality.', history:'Ashwagandha has been used in Ayurveda for over 3000 years.', materials:'Certified organic Ashwagandha root, rice flour capsule', artisan:'Himalaya Botanical Research Centre', specifications:[{key:'Count',value:'60 capsules'},{key:'Serving',value:'1-2 capsules daily'}] },
  { name:'Brahmi Herbal Hair Oil – 200ml', brand:'Indulekha', category:categoryMap['Ayurveda'], images:[u('1512621776831-3b6c5c1e5b2d')], price:320, discount:0, stock:100, state:'Kerala', craftType:'Herbal Oil Infusion', isMSME:false, isSustainable:true, isFeatured:false, description:'Brahmi, Amla, Neem and Bhringraj slow-infused in sesame oil for strengthening hair roots and reducing hair fall.', history:'Brahmi (Bacopa monnieri) is a classical Ayurvedic nervine.', materials:'Brahmi, Amla, Neem, Bhringraj, sesame oil', artisan:'Indulekha Ayurvedic Research Team', specifications:[{key:'Volume',value:'200ml'},{key:'Use',value:'Apply 2x weekly'}] },
  { name:'Nalpamaradi Turmeric Brightening Oil', brand:'Siddhalepa', category:categoryMap['Ayurveda'], images:[u('1556228578-9c53b12c5b47')], price:1250, discount:0, stock:45, state:'Kerala', craftType:'Classical Oil Preparation', isMSME:false, isSustainable:true, isFeatured:false, description:'15 fig-tree bark formula boiled in coconut oil with turmeric and sesame to remove tan and hyperpigmentation naturally.', history:'Nalpamaradi formula is prescribed in Ashtanga Hridayam.', materials:'15 fig-tree barks, turmeric, sesame, coconut oil', artisan:'Kerala Kottakkal Arya Vaidya Sala', specifications:[{key:'Volume',value:'100ml'},{key:'Use',value:'Before bath, 3x weekly'}] },
  { name:'Triphala Churna Digestive Powder – 200g', brand:'Patanjali', category:categoryMap['Ayurveda'], images:[u('1512621776831-2b6c5c1e5b2d')], price:145, discount:0, stock:150, state:'Uttarakhand', craftType:'Herbal Blend', isMSME:false, isSustainable:true, isFeatured:false, description:'Equal parts Amalaki, Bibhitaki and Haritaki — Ayurveda\'s most prescribed tridoshic formula for digestion and immunity.', history:'Triphala has been prescribed in Ayurvedic texts for over 2000 years.', materials:'Amalaki, Bibhitaki, Haritaki (equal parts)', artisan:'Patanjali Haridwar Research Institute', specifications:[{key:'Weight',value:'200g'},{key:'Use',value:'1 tsp with warm water at bedtime'}] },
  { name:'Chyawanprash Awaleha – 500g', brand:'Baidyanath', category:categoryMap['Ayurveda'], images:[u('1512621776831-4b6c5c1e5b2d')], price:390, discount:5, stock:80, state:'West Bengal', craftType:'Classical Rasayana', isMSME:false, isSustainable:true, isFeatured:false, description:'Classical Ayurvedic rasayana with fresh Amla (20:1 concentrate) as primary ingredient surrounded by 40+ herbs, honey and pure ghee.', history:'Chyawanprash is documented in the Charaka Samhita, 1st century BCE.', materials:'Fresh Amla concentrate, 40 Ayurvedic herbs, honey, ghee', artisan:'Baidyanath Research Institute', specifications:[{key:'Weight',value:'500g'},{key:'Use',value:'1-2 tsp daily with milk'}] },
  { name:'Pure Shilajit Resin – 15g', brand:'Upakarma Ayurveda', category:categoryMap['Ayurveda'], images:[u('1526570207-8b8e3bd3e5aa5')], price:2800, discount:0, stock:30, state:'Uttarakhand', craftType:'Mineral Extraction', isMSME:false, isSustainable:true, isFeatured:false, description:'Grade-A Himalayan Shilajit resin rich in fulvic acid and humic compounds. Formed over thousands of years from compressed Himalayan vegetation.', history:'Shilajit is documented in the Charaka Samhita as a Rasayana.', materials:'Grade-A Himalayan Shilajit resin, purified', artisan:'Himalayan Wellness Sourcing', specifications:[{key:'Weight',value:'15g'},{key:'Use',value:'Rice grain size daily in warm milk'}] },
  { name:'Sandal & Turmeric Ubtan Face Scrub – 100g', brand:'Vedic Naturals', category:categoryMap['Ayurveda'], images:[u('1526570207-9b8e3bd3e5aa5')], price:650, discount:0, stock:60, state:'Karnataka', craftType:'Traditional Ubtan', isMSME:true, isSustainable:true, isFeatured:false, description:'Traditional pre-wedding Ubtan combining sandalwood, turmeric, rose water and chickpea flour for a natural golden glow.', history:'Ubtan is a pre-wedding skincare ritual described in Vedic texts.', materials:'Sandalwood powder, turmeric, rose water, chickpea flour', artisan:'Vedic Naturals Heritage Farm, Coorg', specifications:[{key:'Weight',value:'100g'},{key:'Use',value:'Twice weekly as face mask'}] },
  { name:'Shatavari Powder – Women\'s Wellness 200g', brand:'Organic India', category:categoryMap['Ayurveda'], images:[u('1471193565-5b73dc8e3e01')], price:450, discount:0, stock:70, state:'Rajasthan', craftType:'Herbal Extraction', isMSME:false, isSustainable:true, isFeatured:false, description:'Certified organic Shatavari root powder (Asparagus racemosus) — the primary Ayurvedic adaptogen for women\'s hormonal health.', history:'Shatavari has been used in Ayurveda for 2500 years.', materials:'Certified organic Shatavari root, no fillers', artisan:'Organic India Chhattisgarh Farms', specifications:[{key:'Weight',value:'200g'},{key:'Certification',value:'USDA Organic, NPOP'}] },
  { name:'Mahanarayan Tailam Joint Relief Oil – 200ml', brand:'Kottakkal Arya Vaidya Sala', category:categoryMap['Ayurveda'], images:[u('1526570207-6b8e3bd3e5aa5')], price:860, discount:0, stock:45, state:'Kerala', craftType:'Classical Oil Preparation', isMSME:false, isSustainable:true, isFeatured:false, description:'52-herb classical Ayurvedic formula for vata-dosha joint pain. Prepared via traditional sthavara (slow-infusion) process.', history:'Mahanarayan Tailam is one of the most prescribed Ayurvedic oils.', materials:'52 Ayurvedic herbs, sesame oil base', artisan:'AVS Kottakkal Manufacturing Division', specifications:[{key:'Volume',value:'200ml'},{key:'Use',value:'Apply and massage affected joints'}] },
  { name:'Neem & Tulsi Anti-Acne Face Wash – 100ml', brand:'Biotique', category:categoryMap['Ayurveda'], images:[u('1556228578-7c53b12c5b47')], price:195, discount:0, stock:120, state:'Uttarakhand', craftType:'Herbal Formulation', isMSME:false, isSustainable:true, isFeatured:false, description:'Neem leaf extract and Holy Basil steam-distillate combined with aloe vera for gentle antibacterial face cleansing.', history:'Neem and Tulsi are the foremost Ayurvedic antiseptics.', materials:'Neem leaf extract, Holy Basil steam-distillate, aloe vera', artisan:'Biotique Green Herb Research Lab', specifications:[{key:'Volume',value:'100ml'},{key:'Skin type',value:'Oily/Combination'}] },
  { name:'Ayurvedic Tooth Powder – Vicco Vajradanti', brand:'Vicco', category:categoryMap['Ayurveda'], images:[u('1471193565-7b73dc8e3e01')], price:85, discount:0, stock:200, state:'Maharashtra', craftType:'Herbal Dental Formula', isMSME:false, isSustainable:true, isFeatured:false, description:'Ayurvedic tooth powder with babul bark, catechu, clove oil and lime calcium. India\'s best-selling herbal dental product since 1952.', history:'Vicco Vajradanti has been produced using the same formula since 1952.', materials:'Babul bark, catechu, clove oil, calcium carbonate', artisan:'Vicco Laboratories, Pune', specifications:[{key:'Weight',value:'100g'},{key:'Use',value:'Use instead of toothpaste'}] },

  // ─── KITCHEN ──────────────────────────────────────────────────────────────
  { name:'Teak Masala Spice Box – 12 Compartments', brand:'Rasoi Crafts', category:categoryMap['Kitchen'], images:[u('1565071181-f12cb8f0ad27')], price:1250, discount:0, stock:35, state:'Karnataka', craftType:'Wood Carving', isMSME:true, isSustainable:true, isFeatured:false, description:'Channapatna-made aged teak masala box with rotating lid and 12 compartments for whole spices. Shellac-finished for food safety.', history:'Teak has been used for spice storage in South India for centuries.', materials:'Aged teak, organic shellac finish, brass clasp', artisan:'Channapatna Heritage Woodcraft Group', specifications:[{key:'Dimensions',value:'30×25×8 cm'},{key:'Compartments',value:'12'}] },
  { name:'Hand-Hammered Iron Kadai – 30cm', brand:'The Indus Valley', category:categoryMap['Kitchen'], images:[u('1542810603-5b52e33e7e90')], price:2400, discount:8, stock:25, state:'Maharashtra', craftType:'Iron Smithing', isMSME:true, isSustainable:true, isFeatured:true, description:'Pre-seasoned hand-hammered iron kadai that leaches dietary iron into food. Develops a natural non-stick patina with use.', history:'Cast iron has been used in Indian kitchens for millennia.', materials:'Seasoned pig iron, hand-hammered 5mm gauge', artisan:'Maharashtra Iron Smith Guild', specifications:[{key:'Diameter',value:'30 cm'},{key:'Weight',value:'2.2 kg'},{key:'Induction',value:'Not compatible'}] },
  { name:'Brass Mortar & Pestle – Ohkli Set', brand:'Shankh Handicrafts', category:categoryMap['Kitchen'], images:[u('1465014785-b1c918f6ef08')], price:1600, discount:0, stock:30, state:'Uttar Pradesh', craftType:'Brass Casting', isMSME:true, isSustainable:true, isFeatured:false, description:'Food-grade cast brass mortar with sand-cast rough interior for grinding spices. Mirror-polished exterior.', history:'Brass mortars are a Moradabad speciality for over 200 years.', materials:'Food-grade cast brass, sand-cast rough interior', artisan:'Moradabad Brass Craft Cluster', specifications:[{key:'Mortar Diameter',value:'15 cm'},{key:'Pestle Length',value:'22 cm'}] },
  { name:'Coconut Shell Serving Bowls – Set of 4', brand:'Eco Craft Kerala', category:categoryMap['Kitchen'], images:[u('1484564785-2b7df9cb4a9c')], price:890, discount:0, stock:50, state:'Kerala', craftType:'Coconut Shell Craft', isMSME:true, isSustainable:true, isFeatured:false, description:'Zero-waste coconut shell serving bowls polished with organic coconut oil. Naturally food-safe and antibacterial.', history:'South Indian artisans have crafted with coconut shells for centuries.', materials:'Mature coconut shell, organic coconut oil finish', artisan:'Kerala Coconut Craft Society', specifications:[{key:'Diameter',value:'12 cm each'},{key:'Set',value:'4 bowls'}] },
  { name:'Handcrafted Bamboo Serving Tray', brand:'BO Living', category:categoryMap['Kitchen'], images:[u('1484564785-3b7df9cb4a9c')], price:980, discount:0, stock:40, state:'Assam', craftType:'Bamboo Weaving', isMSME:true, isSustainable:true, isFeatured:false, description:'Hand-woven Assamese bamboo serving tray with food-safe varnish and cotton rope handles. Lightweight and durable.', history:'Bamboo craft is a major cottage industry in northeast India.', materials:'Moso bamboo, food-safe varnish, cotton rope handles', artisan:'Northeast India Bamboo Craft Circle', specifications:[{key:'Size',value:'40×30 cm'},{key:'Weight capacity',value:'5 kg'}] },
  { name:'Khurja Blue Pottery Dinner Set – 24 pieces', brand:'Khurja Ceramics', category:categoryMap['Kitchen'], images:[u('1567016379-9b3b4fe9b5f9')], price:4800, discount:12, stock:15, state:'Uttar Pradesh', craftType:'Blue Pottery', isMSME:true, isSustainable:true, isFeatured:false, description:'High-fire kaolin ceramic dinner set painted with underglaze cobalt blue. Lead-free food-safe glaze. Fired at 1200°C.', history:'Khurja is called the Ceramic City of India.', materials:'High-fire kaolin ceramic, lead-free cobalt glaze', artisan:'Khurja Ceramics Manufacturing Cluster', specifications:[{key:'Set',value:'24 pieces'},{key:'Dishwasher',value:'Safe'}] },
  { name:'Hand-Hammered Iron Tawa – 28cm', brand:'The Indus Valley', category:categoryMap['Kitchen'], images:[u('1542810603-7b52e33e7e90')], price:1650, discount:0, stock:30, state:'Maharashtra', craftType:'Iron Smithing', isMSME:true, isSustainable:true, isFeatured:false, description:'Pre-seasoned hand-hammered iron tawa with natural non-stick surface. The micro-texture from hammering holds seasoning perfectly.', history:'Traditional Indian rotis have been cooked on iron tawas for centuries.', materials:'Pre-seasoned cast iron, riveted steel handle', artisan:'Maharashtra Iron Smith Guild', specifications:[{key:'Diameter',value:'28 cm'},{key:'Compatible',value:'Gas, wood fire'}] },
  { name:'Neem Wood Salad Server Set', brand:'Ariro Naturals', category:categoryMap['Kitchen'], images:[u('1465014785-4c7df9cb4a9c')], price:580, discount:0, stock:60, state:'Tamil Nadu', craftType:'Wood Carving', isMSME:true, isSustainable:true, isFeatured:false, description:'Lathe-turned neem wood salad servers with food-safe sesame oil finish. Naturally antimicrobial neem keeps utensils fresh.', history:'Neem wood utensils are recommended in Ayurveda for their antimicrobial properties.', materials:'Organic neem wood, sesame oil finish', artisan:'Ariro Toy Crafts, Chennai', specifications:[{key:'Set',value:'2 pieces (spoon + fork)'},{key:'Length',value:'30 cm'}] },
  { name:'Ceramic Masala Grinder – Blue Pottery', brand:'Jaipur Claycrafts', category:categoryMap['Kitchen'], images:[u('1610830110-7a56c6c9a85a')], price:2100, discount:0, stock:20, state:'Rajasthan', craftType:'Blue Pottery', isMSME:true, isSustainable:true, isFeatured:false, description:'Jaipur Blue Pottery masala grinder with quartz-grit grinding surface. Never imparts metallic taste and keeps spices cool.', history:'Jaipur Blue Pottery uses quartz, not clay — unique worldwide.', materials:'Quartz-body ceramic, cobalt blue glaze', artisan:'Jaipur Blue Pottery Cluster', specifications:[{key:'Capacity',value:'200ml'},{key:'Grinding',value:'Quartz grit interior'}] },
  { name:'Stainless Steel 4-Tier Tiffin Box', brand:'Milton', category:categoryMap['Kitchen'], images:[u('1484564785-4b7df9cb4a9c')], price:1200, discount:5, stock:80, state:'Gujarat', craftType:'Steel Fabrication', isMSME:false, isSustainable:true, isFeatured:false, description:'18/8 food-grade stainless steel 4-tier tiffin with snap-lock lids. Inspired by Mumbai\'s legendary dabbawala system.', history:'The Indian tiffin box has been used by Mumbai dabbawalas for 130+ years.', materials:'18/8 food-grade stainless steel, BPA-free lids', artisan:'Milton India Manufacturing Division', specifications:[{key:'Tiers',value:'4'},{key:'Capacity',value:'4×500ml'},{key:'Dishwasher',value:'Safe'}] },
  { name:'Copper Tongue Cleaner – Set of 2', brand:'Puja Store', category:categoryMap['Kitchen'], images:[u('1465014785-3c7df9cb4a9c')], price:240, discount:0, stock:120, state:'Rajasthan', craftType:'Copper Craft', isMSME:true, isSustainable:true, isFeatured:false, description:'99.9% pure food-grade copper tongue scrapers. Ayurveda prescribes daily tongue scraping with copper for oral health.', history:'Copper tongue scraping (Jihwa Prakshalana) is documented in ancient Ayurvedic texts.', materials:'99.9% pure food-grade copper', artisan:'Jaipur Copper Artisan Collective', specifications:[{key:'Set',value:'2 tongue cleaners'},{key:'Material',value:'Pure copper, no plastic'}] },
  { name:'Urli Panchaloha Rice Cooker – Traditional', brand:'Mohan Lal Sons', category:categoryMap['Kitchen'], images:[u('1542810603-6b52e33e7e90')], price:4200, discount:0, stock:10, state:'Kerala', craftType:'Panchaloha Casting', isMSME:false, isSustainable:false, isFeatured:false, description:'Panchaloha five-metal cooking vessel prescribed in Ayurvedic dietetics. Bell-metal finish resists corrosion for decades.', history:'Panchaloha vessels are prescribed in Charaka Samhita for cooking.', materials:'Panchaloha: copper, brass, tin, lead-free zinc, iron', artisan:'Thrissur Bell Metal Cast Society', specifications:[{key:'Capacity',value:'3 litres'},{key:'Compatible',value:'Wood fire, gas'}] },
  { name:'Bamboo Chopping Board – Antimicrobial', brand:'Eco Craft Kerala', category:categoryMap['Kitchen'], images:[u('1484564785-5b7df9cb4a9c')], price:680, discount:0, stock:65, state:'Kerala', craftType:'Bamboo Craft', isMSME:true, isSustainable:true, isFeatured:false, description:'Eco-friendly bamboo chopping board. Bamboo is naturally harder and more antimicrobial than hardwood. Juice groove included.', history:'Bamboo has been used as a kitchen material in India for millennia.', materials:'Solid bamboo, food-safe linseed oil', artisan:'Kerala Bamboo Craft Society', specifications:[{key:'Size',value:'40×25 cm'},{key:'Thickness',value:'2 cm'}] },
  { name:'Rajasthani Lac Bangle Tray Organiser', brand:'Craft Fair India', category:categoryMap['Kitchen'], images:[u('1568702135-87af5b0f44d6')], price:1100, discount:0, stock:30, state:'Rajasthan', craftType:'Lacquerware', isMSME:true, isSustainable:true, isFeatured:false, description:'Sheesham wood lac-turned tray organiser for kitchen spice jars or bangles. Vibrant multi-colour lac resin finish.', history:'Lac-turning is one of Rajasthan\'s oldest craft traditions.', materials:'Sheesham wood, natural lac resin, mineral pigments', artisan:'Jaipur Lac Artisan Co-op', specifications:[{key:'Size',value:'35×20 cm'},{key:'Compartments',value:'4'}] },

  // ─── BOOKS ────────────────────────────────────────────────────────────────
  { name:'The Art of Indian Cooking – Heritage Cookbook', brand:'Rupa Publications', category:categoryMap['Books'], images:[u('1512821099-4fe22e6e7f73')], price:1200, discount:5, stock:50, state:'Delhi', craftType:'Heritage Publishing', isMSME:false, isSustainable:true, isFeatured:false, description:'350+ recipes from India\'s 29-state culinary heritage. From Vedic kitchens to Mughal royal feasts. Includes historical notes.', history:'A comprehensive celebration of India\'s diverse food heritage.', materials:'Acid-free paper, soy-based inks, linen cover', artisan:'Rupa Publications Heritage Division', specifications:[{key:'Pages',value:'450'},{key:'Format',value:'Hardcover'}] },
  { name:'Sarees of India – Photographic Atlas', brand:'Niyogi Books', category:categoryMap['Books'], images:[u('1512821099-5fe22e6e7f73')], price:3800, discount:0, stock:30, state:'Delhi', craftType:'Heritage Publishing', isMSME:false, isSustainable:true, isFeatured:true, description:'340-page photographic record of 108 distinct saree traditions. Loom diagrams, artisan interviews and historical provenance.', history:'A landmark documentation of India\'s textile heritage.', materials:'Coated matte art paper, full-bleed photography', artisan:'Niyogi Books, New Delhi', specifications:[{key:'Pages',value:'340'},{key:'Format',value:'Coffee Table Hardcover'}] },
  { name:'Malgudi Days – R.K. Narayan (Collector\'s Edition)', brand:'Indian Thought Publications', category:categoryMap['Books'], images:[u('1512821099-8fe22e6e7f73')], price:1800, discount:0, stock:40, state:'Karnataka', craftType:'Literary Publishing', isMSME:false, isSustainable:true, isFeatured:false, description:'Collector\'s edition of R.K. Narayan\'s beloved 1943 classic with original R.K. Laxman illustrations. Cream-tinted acid-free paper.', history:'First published in 1943, Malgudi Days introduced one of literature\'s most beloved fictional towns.', materials:'Cream acid-free paper, cloth cover', artisan:'Indian Thought Publications, Bengaluru', specifications:[{key:'Pages',value:'320'},{key:'Format',value:'Hardcover with dust jacket'}] },
  { name:'India After Gandhi – Ramachandra Guha', brand:'Harper Collins India', category:categoryMap['Books'], images:[u('1512821099-3ge22e6e7f73')], price:1100, discount:10, stock:60, state:'Karnataka', craftType:'History Publishing', isMSME:false, isSustainable:true, isFeatured:false, description:'A sweeping people\'s history of the Indian Republic from 1947 to 2007. Considered the definitive history of modern India.', history:'Ramachandra Guha is India\'s foremost contemporary historian.', materials:'Recycled acid-free paper, archival ink', artisan:'HarperCollins India, Noida', specifications:[{key:'Pages',value:'950'},{key:'Format',value:'Paperback'}] },
  { name:'Classic Indian Weaves – Textile Heritage Atlas', brand:'Niyogi Books', category:categoryMap['Books'], images:[u('1512821099-6ge22e6e7f73')], price:5600, discount:0, stock:15, state:'Delhi', craftType:'Textile Documentation', isMSME:false, isSustainable:true, isFeatured:false, description:'Documents 200 distinct Indian weaving traditions with museum-quality photography, weaver interviews and GI map of India\'s handlooms.', history:'A definitive reference for India\'s textile heritage.', materials:'280gsm coated art paper, linen quarter-bound cover', artisan:'Niyogi Books Heritage Division', specifications:[{key:'Pages',value:'450'},{key:'Format',value:'Limited collector\'s edition'}] },
  { name:'The Discovery of India – Jawaharlal Nehru', brand:'Penguin Random House', category:categoryMap['Books'], images:[u('1512821099-4ge22e6e7f73')], price:650, discount:5, stock:80, state:'Uttar Pradesh', craftType:'Political History', isMSME:false, isSustainable:true, isFeatured:false, description:'Written in prison in 1944, Nehru traces India\'s civilisational history across 5000 years — philosophy, art, religion and independence.', history:'One of the most important books on Indian civilisation ever written.', materials:'Acid-free paper', artisan:'Penguin Classics India Division', specifications:[{key:'Pages',value:'600'},{key:'Format',value:'Paperback'}] },
  { name:'Devdutt Pattanaik Mythology Box Set – 5 volumes', brand:'Westland Books', category:categoryMap['Books'], images:[u('1512821099-5ge22e6e7f73')], price:2400, discount:8, stock:25, state:'Maharashtra', craftType:'Mythology Publishing', isMSME:false, isSustainable:true, isFeatured:false, description:'Five-volume illustrated mythology set: Vishnu Purana, Shiva Purana, Mahabharata, Ramayana and Devi mythology with modern retellings.', history:'Devdutt Pattanaik is India\'s foremost mythology scholar.', materials:'Art paper, embossed slipcase, bookmark ribbon', artisan:'Westland Books, Mumbai', specifications:[{key:'Volumes',value:'5'},{key:'Format',value:'Paperback box set'}] },
  { name:'A Fine Balance – Rohinton Mistry', brand:'Faber & Faber India', category:categoryMap['Books'], images:[u('1512821099-8ge22e6e7f73')], price:750, discount:0, stock:55, state:'Maharashtra', craftType:'Literary Fiction', isMSME:false, isSustainable:true, isFeatured:false, description:'Booker Prize shortlisted novel set during the Emergency (1975-77). Four strangers in Mumbai exploring caste, class and resilience.', history:'Widely considered one of the greatest Indian novels in English.', materials:'Cream matte paper, printed cloth cover', artisan:'Faber India, Mumbai', specifications:[{key:'Pages',value:'620'},{key:'Format',value:'Paperback'}] },
  { name:'Hand & Spirit – Indian Handicrafts Monograph', brand:'Dastkari Haat Samiti', category:categoryMap['Books'], images:[u('1512821099-2ge22e6e7f73')], price:2200, discount:0, stock:20, state:'Delhi', craftType:'Craft Documentation', isMSME:false, isSustainable:true, isFeatured:false, description:'Documents 80 endangered Indian crafts with master-artisan oral histories, process photographs and market livelihood data.', history:'The definitive monograph on India\'s endangered craft traditions.', materials:'Handmade cotton rag paper, archival photographs', artisan:'Dastkari Haat Samiti Press', specifications:[{key:'Pages',value:'320'},{key:'Format',value:'Hardcover'}] },
  { name:'The Palace of Illusions – Chitra Banerjee Divakaruni', brand:'Picador India', category:categoryMap['Books'], images:[u('1512821099-7ge22e6e7f73')], price:550, discount:5, stock:70, state:'West Bengal', craftType:'Literary Fiction', isMSME:false, isSustainable:true, isFeatured:false, description:'A feminist retelling of the Mahabharata through Draupadi\'s eyes. Over two million copies sold worldwide.', history:'One of the most celebrated feminist retellings of Indian mythology.', materials:'FSC-certified paper, plant-based inks', artisan:'Pan Macmillan India, Delhi', specifications:[{key:'Pages',value:'360'},{key:'Format',value:'Paperback'}] },
  { name:'Lost Cities of the Indus – Archaeological Study', brand:'Oxford University Press', category:categoryMap['Books'], images:[u('1512821099-6fe22e6e7f73')], price:2600, discount:0, stock:25, state:'Delhi', craftType:'Academic Publishing', isMSME:false, isSustainable:true, isFeatured:false, description:'Rigorous survey of Harappan civilisation sites from Rakhigarhi to Lothal. Examines craft production, urban planning and metallurgy.', history:'The Indus Valley Civilisation is one of the world\'s earliest urban cultures.', materials:'FSC-certified paper, archival ink', artisan:'OUP India Press, Chennai', specifications:[{key:'Pages',value:'480'},{key:'Format',value:'Hardcover academic'}] },
  { name:'Miniature Paintings of Rajasthan – Illustrated', brand:'Indira Gandhi National Centre', category:categoryMap['Books'], images:[u('1512821099-9fe22e6e7f73')], price:4200, discount:0, stock:12, state:'Delhi', craftType:'Academic Publishing', isMSME:false, isSustainable:true, isFeatured:false, description:'Scholarly volume documenting 500+ miniature paintings from Bundi, Mewar, Marwar and Amber schools. Previously unpublished works.', history:'Rajasthani miniature painting reached its peak under the Mughal empire.', materials:'Archival coated paper, museum-quality printing', artisan:'IGNCA Print Division, New Delhi', specifications:[{key:'Pages',value:'380'},{key:'Format',value:'Large format hardcover'}] },
  { name:'Yoga: The Science of the Soul – Patanjali Commentary', brand:'Penguin Random House', category:categoryMap['Books'], images:[u('1512821099-7fe22e6e7f73')], price:450, discount:0, stock:100, state:'Maharashtra', craftType:'Spiritual Publishing', isMSME:false, isSustainable:true, isFeatured:false, description:'Osho\'s translation and commentary on Patanjali\'s Yoga Sutras. All 196 aphorisms with word-by-word translation and psychological interpretation.', history:'Patanjali\'s Yoga Sutras were compiled around 400 CE.', materials:'Recycled paper, plant-based inks', artisan:'Penguin Books India, Mumbai', specifications:[{key:'Pages',value:'500'},{key:'Format',value:'Paperback'}] },
  { name:'The Argumentative Indian – Amartya Sen', brand:'Penguin Books India', category:categoryMap['Books'], images:[u('1512821099-0ge22e6e7f73')], price:599, discount:5, stock:65, state:'West Bengal', craftType:'Non-fiction Publishing', isMSME:false, isSustainable:true, isFeatured:false, description:'Nobel laureate Amartya Sen\'s examination of India\'s tradition of public reasoning, pluralism and democratic values across 5000 years.', history:'Winner of Nobel Prize in Economics, Amartya Sen is one of India\'s greatest intellectuals.', materials:'Recycled paper, soy-based inks', artisan:'Penguin Books India, Mumbai', specifications:[{key:'Pages',value:'420'},{key:'Format',value:'Paperback'}] },
  { name:'Curry: A Tale of Cooks & Conquerors', brand:'Westland Books', category:categoryMap['Books'], images:[u('1512821099-1ge22e6e7f73')], price:750, discount:0, stock:45, state:'Maharashtra', craftType:'Food History Publishing', isMSME:false, isSustainable:true, isFeatured:false, description:'The history of curry from Mughal court kitchens through the British Raj spice trade to global proliferation as a culinary icon.', history:'One of the most celebrated food history books about Indian cuisine.', materials:'Acid-free paper, food-safe embossed cover', artisan:'Westland Books, Mumbai', specifications:[{key:'Pages',value:'340'},{key:'Format',value:'Paperback'}] },
];

const connectDB = async () => {
  await mongoose.connect(process.env.MONGO_URI);
  console.log('MongoDB connected for seeding');
};

const seed = async () => {
  await connectDB();

  // Clear existing data
  console.log('Clearing existing data...');
  await Promise.all([
    User.deleteMany(),
    Product.deleteMany(),
    Category.deleteMany(),
    Order.deleteMany(),
    Cart.deleteMany(),
    Wishlist.deleteMany(),
  ]);

  // Seed admin user
  const salt = await bcrypt.genSalt(10);
  const hashedPassword = await bcrypt.hash('Admin@123', salt);
  const adminUser = await User.create({
    name: 'Admin',
    email: 'admin@shopez.com',
    password: hashedPassword,
    role: 'admin',
  });
  console.log(`Admin user created: ${adminUser.email}`);

  // Seed categories
  const categories = await Category.insertMany(CATEGORIES_DATA);
  const categoryMap = {};
  categories.forEach((c) => { categoryMap[c.name] = c._id; });
  console.log(`${categories.length} categories seeded`);

  // Seed products
  const products = buildProducts(categoryMap);
  await Product.insertMany(products);
  console.log(`${products.length} products seeded`);

  console.log('\n✅ Seed complete!');
  console.log('Admin credentials: admin@shopez.com / Admin@123');
  process.exit(0);
};

seed().catch((err) => {
  console.error('Seed failed:', err);
  process.exit(1);
});
